{{- $service_account_name := .Values.serviceAccount.name | required ".Values.serviceAccount.name is required." -}}
{{- $namespace := .Values.serviceAccount.namespace | default "kube-system" -}}
{{- $account_id := .Values.aws.account.id | required ".Values.aws.account.id is required." -}}
{{- $account_partition := .Values.aws.account.partition | required ".Values.aws.account.partition is required." -}}
{{- $role_name := .Values.aws.role_name | required ".Values.aws.role_name is required." -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ $service_account_name }}
  namespace: {{ $namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:{{ $account_partition }}:iam::{{ $account_id }}:role/{{ $role_name }}"
