---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridtest
  namespace: awsauthtest
  labels:
    name: hybridtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hybridtest
  template:
    metadata:
      labels:
        name: hybridtest
    spec:
      serviceAccountName: hybridtest
      containers:
        - image: public.ecr.aws/aws-cli/aws-cli:2.17.61
          name: awscli
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
