---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podidentitytest
  namespace: awsauthtest
  labels:
    name: podidentitytest
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: podidentitytest
      containers:
        - command:
            - "/bin/sh"
            - "-c"
            - "while true; do cat /init-container-msg-mount-path/this; sleep 5; done"
          image: public.ecr.aws/aws-cli/aws-cli:2.17.61
          name: awscli
          command: [""]
          args: ["sleep", "10000"]
