---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podidentitytest
  namespace: awsauthtest
  labels:
    name: podidentitytest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podidentitytest
  template:
    spec:
      serviceAccountName: podidentitytest
      metadata:
        labels:
            name: podidentitytest
      containers:
        - image: public.ecr.aws/aws-cli/aws-cli:2.17.61
          name: awscli
          command: [""]
          args: ["sleep", "10000"]
